image: gitpod/workspace-full

tasks:
  - init: |
      git config lfs.https://github.com/DaanJansen94/NF_pipeline.git/info/lfs.locksverify false
      export TZ=Europe/London
      sudo apt-get update
      sudo DEBIAN_FRONTEND=noninteractive
      sudo apt-get install -y tzdata apt-utils build-essential libseccomp-dev pkg-config squashfs-tools cryptsetup
      wget https://github.com/apptainer/singularity/releases/download/v3.8.5/singularity-3.8.5.tar.gz
      tar -xzf singularity-3.8.5.tar.gz
      cd singularity-3.8.5
      ./mconfig
      make -C builddir
      sudo make -C builddir install
      cd ..
      rm -rf singularity-3.8.5 singularity-3.8.5.tar.gz

      # nextflow
      curl -s https://get.nextflow.io | bash
      sudo mv nextflow /usr/local/bin/
    command: echo "Nextflow and Singularity installed"