image: gitpod/workspace-full

tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y build-essential libseccomp-dev pkg-config squashfs-tools cryptsetup
      wget https://github.com/hpcng/singularity/releases/download/v3.8.5/singularity-ce-3.8.5.tar.gz
      tar -xzf singularity-ce-3.8.5.tar.gz
      cd singularity-ce-3.8.5
      ./mconfig
      make -C builddir
      sudo make -C builddir install
      cd ..
      rm -rf singularity-ce-3.8.5 singularity-ce-3.8.5.tar.gz
      curl -s https://get.nextflow.io | bash
      sudo mv nextflow /usr/local/bin/
    command: echo "Nextflow and Singularity installed"

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
    - eamodio.gitlens
    - ms-vscode-remote.remote-containers
