image: gitpod/workspace-full

tasks:
  - name: Install Nextflow and Set Permissions
    command: |
      curl -s https://get.nextflow.io | bash &&
      sudo mv nextflow /usr/local/bin/
      echo "Nextflow installed"

      chmod +x /workspace/nextflow-metatropics-demo/nf-metatropics/bin/produce_fasta.pl
      chmod +x /workspace/nextflow-metatropics-demo/nf-metatropics/bin/adding_bcfdepth_V2.pl

port: 
-port: 3000
  onOpen: open-browser
  
vscode:
  extensions: # based on nf-core.nf-core-extensionpack
    - esbenp.prettier-vscode # Markdown/CommonMark linting and style checking for Visual Studio Code
