input: /workspace/nextflow-metatropics-demo/Input/mpox.csv
outdir: /workspace/nextflow-metatropics-demo/Output
fasta: /workspace/nextflow-metatropics-demo/Databases/Human/Human_genome.fa
dbmeta: /workspace/nextflow-metatropics-demo/Databases/Viral_Refseq
minLength: 200
pair: true
front: 18
tail: 18
